/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zju.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zju.models.V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirrorBackendRef;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * RequestMirror defines a schema for a filter that mirrors requests. Requests are sent to the specified destination, but responses from that destination are ignored.   Support: Extended
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-10T06:17:41.022715Z[Etc/UTC]")
public class V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror {
  public static final String SERIALIZED_NAME_BACKEND_REF = "backendRef";
  @SerializedName(SERIALIZED_NAME_BACKEND_REF)
  private V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirrorBackendRef backendRef;

  public V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror() {
  }

  public V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror backendRef(V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirrorBackendRef backendRef) {
    
    this.backendRef = backendRef;
    return this;
  }

   /**
   * Get backendRef
   * @return backendRef
  **/
  @jakarta.annotation.Nonnull
  public V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirrorBackendRef getBackendRef() {
    return backendRef;
  }


  public void setBackendRef(V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirrorBackendRef backendRef) {
    this.backendRef = backendRef;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror v1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror = (V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror) o;
    return Objects.equals(this.backendRef, v1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror.backendRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backendRef);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror {\n");
    sb.append("    backendRef: ").append(toIndentedString(backendRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("backendRef");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("backendRef");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror is not found in the empty JSON string", V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `backendRef`
      V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirrorBackendRef.validateJsonElement(jsonObj.get("backendRef"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror>() {
           @Override
           public void write(JsonWriter out, V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror
  * @throws IOException if the JSON string is invalid with respect to V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror
  */
  public static V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror.class);
  }

 /**
  * Convert an instance of V1alpha2HTTPRouteSpecRulesInnerBackendRefsInnerFiltersInnerRequestMirror to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

